Wrap target frame map in `domEvent` with a read lock
chromedp/chromedp pull request #1111
Opened 2022-07-12 20:44 UTC by WalkerGriggs

This PR wraps the `t.frames` read in `Target#domEvent` with an read lock

Related issue: #1110

2022-07-13 00:23 UTC, ZekeLu commented
@WalkerGriggs Good catch! Thank you very much!

How did you find the issue? Is it possible to add a regress test for this issue? It's good to have one. But it's also okay to submit the fix without a regress test if it's hard/impossible to write the test.

2022-07-13 00:31 UTC, ZekeLu commented
The failed check is due to #1105, we can ignore it here.

BTW, can you change the commit message to `avoid concurrent map read in (*Target).domEvent`?

2022-07-13 03:23 UTC, ZekeLu commented
> I can spend more time digging tomorrow if that's valuable information.

Please do digging more so that we can understand the issue better. Can you run your app with the `--race` flag? It will give more details.

> Spitballing here, but could two main event loops run in parallel if Run was called multiple times given the same target?

I'm not sure what will happen in this case, but I think we should avoid doing it. Is there a use case that you need to call `Run` in parallel?

2022-07-13 15:32 UTC, WalkerGriggs commented
> Please do digging more so that we can understand the issue better.

Can do. This is part of a system that has been running for months (maybe years now), and this is the first occurrence. We've dumped the goroutines when it panicked, so maybe that'll reveal something.

> Can you run your app with the `--race` flag? It will give more details.

Maybe, but unlikely.

> I'm not sure what will happen in this case, but I think we should avoid doing it. Is there a use case that you need to call `Run` in parallel?

Oh, we avoid that; no use case here. Just throwing out some ideas, though probably not useful until we narrow things down.

2023-02-22 18:14 UTC, WalkerGriggs commented
@ZekeLu -- following up on this. We just ran into this same issue again. I would like to rebase to the latest master and merge this change in if possible.

2023-02-23 00:42 UTC, ZekeLu commented
Do you have more information to share this time?

> fatal error: concurrent map read and map write

I just took a quick look. There are only 3 map writes:

https://github.com/chromedp/chromedp/blob/1738691f6ebd5f448369e81d51aa81ff5cf6d14a/target.go#L298-L305

https://github.com/chromedp/chromedp/blob/1738691f6ebd5f448369e81d51aa81ff5cf6d14a/target.go#L345-L354

https://github.com/chromedp/chromedp/blob/1738691f6ebd5f448369e81d51aa81ff5cf6d14a/chromedp.go#L290-L298

The first 2 writes are in the `pageEvent` func. But `pageEvent` and `domEvent` won't run at the same time for the same target. So it's most likely that it is the write in `newTarget` to blame.

If this is the case, we should add a write lock here too. I think it's possible to write a test for this case. Would you like to give it a try?

BTW, the write in `newTarget` only happen when you use `chromedp.WithTargetID`. Have your used `chromedp.WithTargetID` in your project?

2023-03-06 18:12 UTC, WalkerGriggs commented
> Do you have more information to share this time?

@ZekeLu, unfortunately not enough to confidently reproduce this specific error case in tests. The stack traces are thin at best, and these rare occurrences are causing issues in production.

Locking the frame read when there's the risk of concurrent access feels like a quick win here.

> BTW, the write in newTarget only happen when you use chromedp.WithTargetID. Have your used chromedp.WithTargetID in your project?

We do use `WithTargetID` when we create a new context. This line is the top-most chromdp specific line in the stacktrace. I can probably put together the full trace dump, but might have to redact some chunks.

```
	tabCtx, _ := chromedp.NewContext(dpctx, chromedp.WithTargetID(newTarget.TargetID))
```

2023-04-14 06:05 UTC, ZekeLu requested changes
We should take the changes from #1297 too.

And if you don't mind, please fix other minor issues related `frameMu` listed below:

1. it seems  that a read lock is enough:

https://github.com/chromedp/chromedp/blob/0b936bf02d9c76500cc82f0c809071df2ca97733/chromedp.go#L622-L624

2. `// frameMu protects frames, execContexts, and cur.`
https://github.com/chromedp/chromedp/blob/0b936bf02d9c76500cc82f0c809071df2ca97733/target.go#L31

2023-04-14 16:53 UTC, WalkerGriggs commented
Rebased to master (0b936bf02d9c76500cc82f0c809071df2ca97733).

@ZekeLu making those changes now

2023-04-15 00:37 UTC, WalkerGriggs commented
@ZekeLu I noticed you've triggered the tests few times which all leak a similar temp dir.

I ran the tests locally with the `./contrib/docker-test.sh` which all pass. Let me know if I can do anything to help validate the changes / get this PR over the line though -- happy to jump in

2023-04-15 01:55 UTC, ZekeLu approved these changes
Thank you @WalkerGriggs and @xiusin!

2023-04-15 02:17 UTC, merged