FEATURE: make polling interval configurable
chromedp/chromedp pull request #1159
Opened 2022-09-13 21:14 UTC by taylorchu

2022-09-14 18:34 UTC, taylorchu commented
@kenshaw @ZekeLu thanks!

2022-09-15 04:36 UTC, ZekeLu commented
@taylorchu Thank you for your contribution!

I'm worried that `WithContextPollingInterval` will make the users confusing since we already have `WithPollingInterval`.

https://github.com/chromedp/chromedp/blob/d52f142d01c7ab3391991d23d957e5f9b774ee94/poll.go#L144-L150

BTW, it seems  that you are aware of the `chromedp.PollAction`. Do you have a use case that can not  be implemented with `chromedp.PollAction`?

My rule of thumb is: I will use the `chromedp.QueryAction` first because it's easy. The retry logic is to make sure it will give me the result. But if it needs several retries, I will consider using the `chromedp.PollAction.

2022-09-15 06:20 UTC, taylorchu commented
Use case: After running a few "sequential" prepare steps, our chromedp will then wait for the site to do a list of unordered things. We start one goroutine for each of these things to wait for them to happen, perform actions, and then wait for them to happen again.

We initially didn't know chromedp polls at this rapid rate, and don't want to rewrite with poll action now because it is essentially a huge refactor from go to pure js. It seems like simply making this 5ms configurable is good enough for most people.

I also think the function name could be better. If you have a suggestion, let me know.

2022-09-15 06:25 UTC, taylorchu commented
In production, we have about 10 watchdog goroutines. Polling at 1s vs 5ms improves cpu usage a lot.

2022-09-15 06:36 UTC, ZekeLu commented
> and don't want to rewrite with poll action now because it is essentially a huge refactor from go to pure js

I think the `chromedp.PollAction` + js is better since it requires less round trip. Let's assume that the project is created from scratch, do you think `WithContextPollingInterval` + go is better? And why?

2022-09-15 16:22 UTC, taylorchu commented
yes. It allows experimentation to production with the exact same code. Also the polling interval should be configurable for performance reason in general.

2022-09-15 16:42 UTC, ZekeLu commented
> It allows experimentation to production with the exact same code.

I think it holds true for the two approaches.

> Also the polling interval should be configurable for performance reason in general.

`chromedp.PollAction` has 3 polling modes:

- in requestAnimationFrame callback
- with a specified interval
- on every DOM mutation

See https://pkg.go.dev/github.com/chromedp/chromedp#hdr-Polling_Options

I want to see an example that `WithContextPollingInterval` is better than the current available solutions.

2022-09-15 18:03 UTC, taylorchu commented
> I think it holds true for both approaches.

https://github.com/chromedp/examples/blob/master/click/main.go#L27 

How do you convert this to poll action without converting go to js?

2022-09-15 18:19 UTC, taylorchu commented
The only change I made to reduce cpu usage significantly in comparison:
```
taskCtx, cancel := chromedp.NewContext(allocCtx, chromedp.WithContextPollingInterval(time.Second))
```

2022-09-16 05:16 UTC, ZekeLu commented
> How do you convert this to poll action without converting go to js?

I can't. The poll action works with js expressions. Do you mean that you don't want to use js at all?

For the record, if I have to implement it with the poll action, I will do it like this:

```diff
-		chromedp.WaitVisible(`body > footer`),
+		chromedp.Poll(`document.querySelector("body > footer") !== null`, nil, chromedp.WithPollingMutation()),
```

Notes:

1. For this page, `body > footer` is created soon after the page is loaded. Both the calls are not needed and could be removed totally.
2. `chromedp.WaitVisible("body > footer")` can be improved by using `chromedp.WaitReady("body > footer", chromedp.ByQuery)` instead.

2022-09-17 02:04 UTC, taylorchu commented
I simplified the pr, and added a test.

2022-09-17 04:30 UTC, ZekeLu commented
Thanks. Now the PR looks more reasonable. I would limit the change to the query action:

```diff
index 53a4206..f494945 100644
--- a/query.go
+++ b/query.go
@@ -29,6 +29,7 @@ type Selector struct {
    sel           interface{}
    fromNode      *cdp.Node
    exp           int
+   retryInterval time.Duration
    by            func(context.Context, *cdp.Node) ([]cdp.NodeID, error)
    wait          func(context.Context, *cdp.Frame, runtime.ExecutionContextID, ...cdp.NodeID) ([]*cdp.Node, error)
    after         func(context.Context, runtime.ExecutionContextID, ...*cdp.Node) error
@@ -130,6 +131,7 @@ func Query(sel interface{}, opts ...QueryOption) QueryAction {
    s := &Selector{
        sel:           sel,
        exp:           1,
+       retryInterval: 5 * time.Millisecond,
    }
 
    // apply options
@@ -155,7 +157,7 @@ func (s *Selector) Do(ctx context.Context) error {
    if t == nil {
        return ErrInvalidTarget
    }
-   return retryWithSleep(ctx, 5*time.Millisecond, func(ctx context.Context) (bool, error) {
+   return retryWithSleep(ctx, s.retryInterval, func(ctx context.Context) (bool, error) {
        frame, root, execCtx, ok := t.ensureFrame()
        if !ok {
            return false, nil
@@ -254,6 +256,12 @@ func (s *Selector) waitReady(check func(context.Context, runtime.ExecutionContex
    }
 }
 
+func RetryInterval(interval time.Duration) QueryOption {
+   return func(s *Selector) {
+       s.retryInterval = interval
+   }
+}
```

The caller has to pass the `chromedp.RetryInterval` option to the query action for which it wants a different retry interval. It's a little annoying, but it gives the caller finer grain control.

2022-09-17 06:50 UTC, ZekeLu requested changes
Thank you! I have added some comments. Please take a look.

2022-09-17 06:50 UTC, ZekeLu commented on query.go
> +// By default, a query retries every 5ms.
How about:

```
// RetryInterval is an element query action option to set the retry interval to specify
// how often it should retry when it failed to select the target element(s).
//
// The default value is 5ms.
```

2022-09-17 06:50 UTC, ZekeLu commented on query_test.go
> +	}
Use sub tests instead. See

https://github.com/chromedp/chromedp/blob/d52f142d01c7ab3391991d23d957e5f9b774ee94/query_test.go#L221-L231

2022-09-17 06:50 UTC, ZekeLu commented on query_test.go
> +		ctx, cancel := context.WithTimeout(ctx, time.Second)
reduce the timeout. I think 100ms should be enough.

2022-09-17 06:50 UTC, ZekeLu commented on query_test.go
> +	count := func(context.Context, *cdp.Frame, cdpruntime.ExecutionContextID, ...cdp.NodeID) ([]*cdp.Node, error) {
Add comment to the count function

```go
// count is a wait function that makes the query always fail and count the number of retries
count := ....
```

2022-09-17 06:50 UTC, ZekeLu commented on query_test.go
> +		if err := Run(ctx, Query("//input", WaitFunc(count))); err != nil && !errors.Is(err, context.DeadlineExceeded) {
Wrap long line

2022-09-17 06:50 UTC, ZekeLu commented on query_test.go
> +		ctx, cancel := context.WithTimeout(ctx, time.Second)
ditto

2022-09-17 06:50 UTC, ZekeLu commented on query_test.go
> +		if err := Run(ctx, Query("//input", WaitFunc(count), RetryInterval(10*time.Second))); err != nil && !errors.Is(err, context.DeadlineExceeded) {
ditto

2022-09-17 11:28 UTC, ZekeLu commented
```go
func TestRetryInterval(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name         string
		opts         []QueryOption
		wantCountMin int
		wantCountMax int
	}{
		{
			name: "default",
			opts: []QueryOption{},
			// in 100ms
			wantCountMin: 10,
			wantCountMax: 20,
		},
		{
			name: "large interval",
			opts: []QueryOption{RetryInterval(60 * time.Millisecond)},
			// in 100ms
			wantCountMin: 2,
			wantCountMax: 2,
		},
	}

	ctx, cancel := testAllocate(t, "js.html")
	defer cancel()

	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			retryCount := 0

			// count is a wait function that makes the query always fail and
			// counts the number of retries. Note that the wait func is called
			// only after the number of result nodes >= s.exp .
			count := WaitFunc(
				func(ctx context.Context, f *cdp.Frame, eci cdpruntime.ExecutionContextID, ni ...cdp.NodeID) ([]*cdp.Node, error) {
					retryCount += 1
					return nil, ErrInvalidTarget
				},
			)

			ctx, cancel := context.WithTimeout(ctx, 100*time.Millisecond)
			defer cancel()

			opts := append(tc.opts, count)
			err := Run(ctx, Query("//input", opts...))

			if err == nil || !errors.Is(err, context.DeadlineExceeded) {
				t.Fatalf("want error context.DeadlineExceeded, got: %v", err)
			}
			if retryCount < tc.wantCountMin {
				t.Fatalf("want retry count > %d, got: %d", tc.wantCountMin, retryCount)
			}
			if retryCount > tc.wantCountMax {
				t.Fatalf("want retry count < %d, got: %d", tc.wantCountMax, retryCount)
			}
		})
	}
}
```

2022-09-17 15:33 UTC, ZekeLu approved these changes

2022-09-17 15:45 UTC, merged

2022-09-17 15:45 UTC, ZekeLu commented
Thank you!